name: Enforce Dev to Main

on:
  pull_request:
    branches: [ main ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from dev branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Error: Pull requests to 'main' can only come from 'dev' branch."
            echo "Your PR is from: ${{ github.head_ref }}"
            exit 1
          else
            echo "✅ PR is correctly coming from dev branch"
          fi